export interface SeedDiagnosis {
  id: string;
  created_at: string;
  state: string;
  district: string;
  crop_type: string;
  disease: string;
  is_healthy: boolean;
  confidence: 'High' | 'Moderate';
  diagnosis_text: string;
  recommendation: string;
  language: 'hi' | 'bn' | 'en';
  image_url: string;
  temperature_c: number;
  humidity_percent: number;
  rain_probability: number;
}

export const SEED_DIAGNOSES: SeedDiagnosis[] = [
  // Maharashtra
  {
    id: 'diag-mh-01',
    created_at: '2026-09-05T08:30:00Z',
    state: 'Maharashtra',
    district: 'Nashik',
    crop_type: 'Tomato',
    disease: 'Early Blight (अगेती झुलसा)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Early Blight: Dark concentric spots observed on lower foliage.',
    recommendation: 'Remove infected lower leaves. Spray neem oil solution (5ml/L) or copper fungicide. Avoid overhead watering.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0012b9d2-2130-4a06-a834-b1f3af34f57e___RS_Erly.B%208389.JPG',
    temperature_c: 25.8,
    humidity_percent: 76,
    rain_probability: 100,
  },
  {
    id: 'diag-mh-02',
    created_at: '2026-09-04T11:15:00Z',
    state: 'Maharashtra',
    district: 'Pune',
    crop_type: 'Soybean',
    disease: 'Soybean Rust (सोयाबीन गेरुआ)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Soybean Rust: Small brown pustules on undersides of leaves.',
    recommendation: 'Ensure field drainage. Apply hexaconazole or mancozeb early morning. Avoid late afternoon irrigation.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0034a551-9512-44e5-ba6c-827f85ecc688___RS_Erly.B%209432.JPG',
    temperature_c: 27.2,
    humidity_percent: 68,
    rain_probability: 45,
  },
  {
    id: 'diag-mh-03',
    created_at: '2026-09-03T15:40:00Z',
    state: 'Maharashtra',
    district: 'Kolhapur',
    crop_type: 'Sugarcane',
    disease: 'Looks Healthy (स्वस्थ गन्ना)',
    is_healthy: true,
    confidence: 'High',
    diagnosis_text: 'Vigorous cane shoots with healthy deep green leaves.',
    recommendation: 'Canes are developing well. Continue scheduled furrow irrigation and earthening up.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___healthy/000146ff-92a4-4db6-90ad-8fce2ae4fddd___GH_HL%20Leaf%20259.1.JPG',
    temperature_c: 26.5,
    humidity_percent: 82,
    rain_probability: 70,
  },
  {
    id: 'diag-mh-04',
    created_at: '2026-09-02T09:20:00Z',
    state: 'Maharashtra',
    district: 'Nashik',
    crop_type: 'Onion',
    disease: 'Purple Blotch (बैंगनी धब्बा)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Purple Blotch: Water soaked lesions turning purplish brown on onion scapes.',
    recommendation: 'Spray chlorothalonil or propiconazole with sticker. Avoid water stagnation.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0012b9d2-2130-4a06-a834-b1f3af34f57e___RS_Erly.B%208389.JPG',
    temperature_c: 24.9,
    humidity_percent: 79,
    rain_probability: 85,
  },

  // Punjab
  {
    id: 'diag-pb-01',
    created_at: '2026-09-05T07:10:00Z',
    state: 'Punjab',
    district: 'Ludhiana',
    crop_type: 'Wheat',
    disease: 'Yellow Rust (पीला रतुआ)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Yellow Rust: Linear stripes of yellowish-orange pustules on leaves.',
    recommendation: 'Spray propiconazole (Tilt 25 EC) @ 1 ml/L immediately. Check adjacent rows for spread.',
    language: 'en',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Corn_(maize)___Common_rust_/RS_Rust%201563.JPG',
    temperature_c: 29.4,
    humidity_percent: 62,
    rain_probability: 15,
  },
  {
    id: 'diag-pb-02',
    created_at: '2026-09-04T16:00:00Z',
    state: 'Punjab',
    district: 'Bathinda',
    crop_type: 'Cotton',
    disease: 'Cotton Leaf Curl Virus (पत्ता मरोड़)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Upward curling of leaves with enation on leaf veins.',
    recommendation: 'Control whitefly vectors using recommended systemic insecticides. Uproot heavily infected plants.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0012b9d2-2130-4a06-a834-b1f3af34f57e___RS_Erly.B%208389.JPG',
    temperature_c: 32.1,
    humidity_percent: 54,
    rain_probability: 10,
  },
  {
    id: 'diag-pb-03',
    created_at: '2026-09-03T10:45:00Z',
    state: 'Punjab',
    district: 'Amritsar',
    crop_type: 'Rice',
    disease: 'Looks Healthy (ਸਿਹਤਮੰਦ ਝੋਨਾ)',
    is_healthy: true,
    confidence: 'High',
    diagnosis_text: 'Healthy tillering stage paddy canopy with clear green foliage.',
    recommendation: 'Maintain 2-3 inches water level. Avoid excess nitrogen fertilization.',
    language: 'en',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___healthy/000146ff-92a4-4db6-90ad-8fce2ae4fddd___GH_HL%20Leaf%20259.1.JPG',
    temperature_c: 28.6,
    humidity_percent: 71,
    rain_probability: 30,
  },
  {
    id: 'diag-pb-04',
    created_at: '2026-09-01T14:15:00Z',
    state: 'Punjab',
    district: 'Jalandhar',
    crop_type: 'Potato',
    disease: 'Late Blight (ਪਿਛੇਤਾ ਝੁਲਸ ਰੋਗ)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Late Blight: Water soaked irregular lesions with white mildew on leaf margins.',
    recommendation: 'Spray metalaxyl + mancozeb (Ridomil MZ) @ 2.5 g/L. Stop field irrigation immediately.',
    language: 'en',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0034a551-9512-44e5-ba6c-827f85ecc688___RS_Erly.B%209432.JPG',
    temperature_c: 27.8,
    humidity_percent: 85,
    rain_probability: 80,
  },

  // West Bengal
  {
    id: 'diag-wb-01',
    created_at: '2026-09-05T06:45:00Z',
    state: 'West Bengal',
    district: 'Hooghly',
    crop_type: 'Potato',
    disease: 'Late Blight (নাবী ধসা)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Late Blight: Rapidly expanding water-soaked necrotic patches with whitish sporulation.',
    recommendation: 'Spray cymoxanil + mancozeb or dimethomorph. Ensure complete soil drainage in lowlands.',
    language: 'bn',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0012b9d2-2130-4a06-a834-b1f3af34f57e___RS_Erly.B%208389.JPG',
    temperature_c: 31.9,
    humidity_percent: 73,
    rain_probability: 97,
  },
  {
    id: 'diag-wb-02',
    created_at: '2026-09-04T08:20:00Z',
    state: 'West Bengal',
    district: 'Burdwan',
    crop_type: 'Rice',
    disease: 'Brown Spot (বাদামি দাগ রোগ)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Brown Spot: Oval sesame seed shaped spots on paddy leaf blades.',
    recommendation: 'Ensure balanced potassium and silicon fertilization. Spray carbendazim + mancozeb.',
    language: 'bn',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Corn_(maize)___Common_rust_/RS_Rust%201563.JPG',
    temperature_c: 30.8,
    humidity_percent: 81,
    rain_probability: 65,
  },
  {
    id: 'diag-wb-03',
    created_at: '2026-09-03T11:50:00Z',
    state: 'West Bengal',
    district: 'Nadia',
    crop_type: 'Tomato',
    disease: 'Looks Healthy (গাছ সম্পূর্ণ সুস্থ)',
    is_healthy: true,
    confidence: 'High',
    diagnosis_text: 'Healthy green foliage with uniform flower bud initiation.',
    recommendation: 'Plants are robust. Continue regular staking and bio-stimulant foliar spray.',
    language: 'bn',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___healthy/000146ff-92a4-4db6-90ad-8fce2ae4fddd___GH_HL%20Leaf%20259.1.JPG',
    temperature_c: 32.4,
    humidity_percent: 69,
    rain_probability: 25,
  },

  // Uttar Pradesh
  {
    id: 'diag-up-01',
    created_at: '2026-09-05T09:15:00Z',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    crop_type: 'Tomato',
    disease: 'Leaf Curl Virus (पर्ण कुंचन)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Stunted bushy growth with severe inward leaf puckering and vein thickening.',
    recommendation: 'Install yellow sticky traps (15 traps/acre) to trap whitefly vectors. Spray neem seed extract.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0012b9d2-2130-4a06-a834-b1f3af34f57e___RS_Erly.B%208389.JPG',
    temperature_c: 33.1,
    humidity_percent: 64,
    rain_probability: 20,
  },
  {
    id: 'diag-up-02',
    created_at: '2026-09-04T13:30:00Z',
    state: 'Uttar Pradesh',
    district: 'Agra',
    crop_type: 'Mustard',
    disease: 'Alternaria Blight (अल्टरनेरिया झुलसा)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Concentric dark target spots on lower mustard foliage and pods.',
    recommendation: 'Apply mancozeb 75 WP @ 2g/L. Maintain plant spacing and avoid over-dense sowing.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0034a551-9512-44e5-ba6c-827f85ecc688___RS_Erly.B%209432.JPG',
    temperature_c: 34.0,
    humidity_percent: 51,
    rain_probability: 10,
  },
  {
    id: 'diag-up-03',
    created_at: '2026-09-02T11:00:00Z',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    crop_type: 'Wheat',
    disease: 'Looks Healthy (स्वस्थ गेहूं)',
    is_healthy: true,
    confidence: 'High',
    diagnosis_text: 'Even stand with green vegetative tillers free of rust pustules.',
    recommendation: 'Foliage is clear. Ensure crown root irrigation at 21 days after sowing.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___healthy/000146ff-92a4-4db6-90ad-8fce2ae4fddd___GH_HL%20Leaf%20259.1.JPG',
    temperature_c: 31.5,
    humidity_percent: 58,
    rain_probability: 15,
  },

  // Madhya Pradesh
  {
    id: 'diag-mp-01',
    created_at: '2026-09-05T08:00:00Z',
    state: 'Madhya Pradesh',
    district: 'Indore',
    crop_type: 'Soybean',
    disease: 'Yellow Mosaic Virus (पीला मोज़ेक)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Mottled chlorotic bright yellow patches scattered across soybean leaf blades.',
    recommendation: 'Rogue out infected plants immediately. Spray acetamiprid or thiamethoxam to control whiteflies.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0012b9d2-2130-4a06-a834-b1f3af34f57e___RS_Erly.B%208389.JPG',
    temperature_c: 28.2,
    humidity_percent: 74,
    rain_probability: 60,
  },
  {
    id: 'diag-mp-02',
    created_at: '2026-09-03T16:10:00Z',
    state: 'Madhya Pradesh',
    district: 'Ujjain',
    crop_type: 'Wheat',
    disease: 'Black Stem Rust (काला तना रतुआ)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Reddish-brown to black elongated pustules on stems and leaf sheaths.',
    recommendation: 'Spray propiconazole 25 EC. Adopt resistant cultivars in subsequent planting cycles.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Corn_(maize)___Common_rust_/RS_Rust%201563.JPG',
    temperature_c: 29.8,
    humidity_percent: 63,
    rain_probability: 20,
  },
  {
    id: 'diag-mp-03',
    created_at: '2026-09-02T14:40:00Z',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    crop_type: 'Corn',
    disease: 'Looks Healthy (स्वस्थ मक्का)',
    is_healthy: true,
    confidence: 'High',
    diagnosis_text: 'Clean maize whorls with no fall armyworm damage or foliar blight.',
    recommendation: 'Crop vigor is optimal. Monitor weekly for any border row pest incursions.',
    language: 'hi',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___healthy/000146ff-92a4-4db6-90ad-8fce2ae4fddd___GH_HL%20Leaf%20259.1.JPG',
    temperature_c: 27.5,
    humidity_percent: 78,
    rain_probability: 50,
  },

  // Karnataka
  {
    id: 'diag-ka-01',
    created_at: '2026-09-05T10:30:00Z',
    state: 'Karnataka',
    district: 'Belagavi',
    crop_type: 'Corn',
    disease: 'Common Rust (ಸಾಮಾನ್ಯ ತುಕ್ಕು ರೋಗ)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Golden-brown powdery pustules on both upper and lower leaf surfaces.',
    recommendation: 'Spray azoxystrobin or mancozeb. Improve intra-row spacing to promote sunlight penetration.',
    language: 'en',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Corn_(maize)___Common_rust_/RS_Rust%201563.JPG',
    temperature_c: 26.2,
    humidity_percent: 88,
    rain_probability: 75,
  },
  {
    id: 'diag-ka-02',
    created_at: '2026-09-04T12:00:00Z',
    state: 'Karnataka',
    district: 'Mysuru',
    crop_type: 'Cotton',
    disease: 'Bacterial Blight (ಬ್ಯಾಕ್ಟೀರಿಯಾದ ರೋಗ)',
    is_healthy: false,
    confidence: 'High',
    diagnosis_text: 'Angular water-soaked leaf spots bounded by veinlets, turning reddish-brown.',
    recommendation: 'Spray copper oxychloride (3g/L) + streptocycline (0.1g/L). Avoid excessive nitrogenous manure.',
    language: 'en',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___Early_blight/0012b9d2-2130-4a06-a834-b1f3af34f57e___RS_Erly.B%208389.JPG',
    temperature_c: 27.9,
    humidity_percent: 70,
    rain_probability: 40,
  },
  {
    id: 'diag-ka-03',
    created_at: '2026-09-01T09:45:00Z',
    state: 'Karnataka',
    district: 'Dharwad',
    crop_type: 'Tomato',
    disease: 'Looks Healthy (ಆರೋಗ್ಯಕರ ಬೆಳೆ)',
    is_healthy: true,
    confidence: 'High',
    diagnosis_text: 'Clean foliage with strong apical shoot extension.',
    recommendation: 'Maintain drip fertigation schedule and inspect lower canopy once weekly.',
    language: 'en',
    image_url: 'https://raw.githubusercontent.com/spMohanty/PlantVillage-Dataset/master/raw/color/Tomato___healthy/000146ff-92a4-4db6-90ad-8fce2ae4fddd___GH_HL%20Leaf%20259.1.JPG',
    temperature_c: 28.0,
    humidity_percent: 65,
    rain_probability: 30,
  },
];
